name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
      - release/*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate config.js
        run: |
          echo "window.CONFIG = {" | tee docs/config.js
          echo "  BRIDGE_SERVICE_URL: '${{ secrets.BRIDGE_SERVICE_URL }}'," | tee -a docs/config.js
          echo "  BRIDGE_SERVICE_REST_PROTOCOL: '${{ secrets.BRIDGE_SERVICE_REST_PROTOCOL }}'," | tee -a docs/config.js
          echo "  BRIDGE_SERVICE_WEB_SOCKET_PROTOCOL: '${{ secrets.BRIDGE_SERVICE_WEB_SOCKET_PROTOCOL }}'" | tee -a docs/config.js
          echo "};" | tee -a docs/config.js

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs
          token: ${{ secrets.GH_PAT }}
