name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
      - release/*

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate config.js
        run: |
          echo "window.CONFIG = {" | tee docs/config.js
          echo "  BRIDGE_SERVICE_URL: '${{ secrets.BRIDGE_SERVICE_URL }}'," | tee -a docs/config.js
          echo "  BRIDGE_SERVICE_REST_PROTOCOL: '${{ secrets.BRIDGE_SERVICE_REST_PROTOCOL }}'," | tee -a docs/config.js
          echo "  BRIDGE_SERVICE_WEB_SOCKET_PROTOCOL: '${{ secrets.BRIDGE_SERVICE_WEB_SOCKET_PROTOCOL }}'" | tee -a docs/config.js
          echo "};" | tee -a docs/config.js

      - name: Upload HTML, CSS, and JS files
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
